# Baby Steps - Algebra

Following:

http://deeplearning.net/software/theano/tutorial/adding.html

## Adding two scalars

In [1]:
import theano.tensor as T
from theano import function

In [2]:
x = T.dscalar('x')
y = T.dscalar('y')
z = x + y
f = function([x, y], z)

In [3]:
f(2, 3)

array(5.0)

In [4]:
f(16.3, 12.1)

array(28.4)

First we defined two symbols (variables) representing quantities we wish to add. The output of `f` is a `numpy.ndarray` with zero dimension. Behind the scenes, `f` was compiled into C code.

### Step 1

In [5]:
x = T.dscalar('x')
y = T.dscalar('y')

In Theano, all symbols must be typed. `T.dscalar` is the type we assign to "0-dimensional arrays of doubles". It is a Theano [Type](http://deeplearning.net/software/theano/extending/graphstructures.html#type).

`dscalar` is not a class. So neither `x` nor `y` are instances of `dscalar`. They are instances of `TensorVariable`.

In [6]:
type(x)

theano.tensor.var.TensorVariable

In [7]:
x.type

TensorType(float64, scalar)

In [8]:
T.dscalar

TensorType(float64, scalar)

In [9]:
x.type is T.dscalar

True

By calling `T.dscalar` with a string argument, we create a _variable_ representing a floating point scalar quantity with the given name. If we provide no argument, the symbol will not be named. Names aren't required, but they are helpful for debugging, etc.

### Step 2

The second step is to combine `x` and `y` into their sum, `z`:

In [10]:
z = x + y

In [11]:
from theano import pp

In [12]:
print pp(z)

(x + y)


### Step 3

Finally, we create a function taking `x` and `y` as inputs and giving `z` as output:

In [13]:
f = function([x, y], z)

The first argument to `function` is the input, and the second is the output. Once we've created it, we may use `f` like a normal Python function.

In [14]:
f(1, 2)

array(3.0)

In [15]:
f(f(1, 2), 3)

array(6.0)

In [16]:
f(f(f(1, 2), 3), 4)

array(10.0)

**Note**: as a shortcut, we may skip step 3 and use a variable's `eval()` method. `eval()` is not as flexible as `function`, but it can still do many things and it doesn't require us to `import` `function`.

In [17]:
z.eval({x: 16.3, y: 12.1})

array(28.4)

In [18]:
z.eval({x: 1, y: z.eval({x: 2, y: 3})})

array(6.0)

`eval()` will be slow the first time we call it on a variable (it needs to compile and call `function` behind the scenes), but subsequent calls on the same variable will be fast.

## Adding two matrices

In [19]:
x = T.dmatrix('x')
y = T.dmatrix('y')
z = x + y
f = function([x, y], z)

`dmatrix` is the Type for matrices of doubles. We may use our function on 2D arrays:

In [20]:
f([[1, 2], [3, 4]], [[10, 20], [30, 40]])

array([[ 11.,  22.],
       [ 33.,  44.]])

The variable is a NumPy array. We may also use NumPys arrays directly as inputs:

In [21]:
import numpy as np

In [22]:
f(np.array([[1, 2], [3, 4]]), np.array([[10, 20], [30, 40]]))

array([[ 11.,  22.],
       [ 33.,  44.]])

In [28]:
f(np.array([[1, 2], [3, 4]]), np.array([[1, 2], [3, 4]]))

array([[ 2.,  4.],
       [ 6.,  8.]])

It is possible to add scalars to matrices, scalars to vectors, etc. The behavior is defined by [broadcasting](http://deeplearning.net/software/theano/library/tensor/basic.html#libdoc-tensor-broadcastable).

The following types are available:

* byte: `bscalar`, `bvector`, `brow`, `bcol`, `btensor3`, `btensor4`
* 16-bit integers: `wscalar`, `wvector`, `wmatrix`, `wrow`, `wcol`, `wtensor3`, `wtensor4`
* 32-bit integers: `iscalar`, `ivector`, `imatrix`, `irow`, `icol`, `itensor3`, `itensor4`
* 64-bit integers: `lscalar`, `lvector`, `lmatrix`, `lrow`, `lcol`, `ltensor3`, `ltensor4`
* float: `fscalar`, `fvector`, `fmatrix`, `frow`, `fcol`, `ftensor3`, `ftensor4`
* double: `dscalar`, `dvector`, `dmatrix`, `drow`, `dcol`, `dtensor3`, `dtensor4`
* complex: `cscalar`, `cvector`, `cmatrix`, `crow`, `ccol`, `ctensor3`, `ctensor4`

This list is not exhaustive. All the types may be found [here](http://deeplearning.net/software/theano/library/tensor/basic.html#libdoc-tensor-creation).

## Exercise

In [30]:
import theano
a = theano.tensor.vector()
out = a + a ** 10
f = theano.function([a], out)
print f([0, 1, 2])

[    0.     2.  1026.]


Modfiy this code to compute `a ** 2 + b ** 2 + 2 * a * b`:

In [31]:
a = theano.tensor.vector()
b = theano.tensor.vector()

out = a ** 2 + b ** 2 + 2 * a * b
f = theano.function([a, b], out)
print f([0, 1, 2], [2, 3, 4])

[  4.  16.  36.]


In [32]:
print f([1, 2], [4, 5])

[ 25.  49.]
